/**
 * 時間変化エフェクトで参照するパラメータカタログ。
 * support が "unsupported" の項目は、開発方針として時間変化生成の対象外です。
 */
const parameterDefinitions = [
  { displayName: "update_period", parameterName: "update_period", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["retrigger", "echo"], effectTypesDisplay: "Re, Ga", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "wave_length", parameterName: "wave_length", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["retrigger", "gate", "wobble", "echo"], effectTypesDisplay: "Re, Ga, Wo, Ec", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "rate", parameterName: "rate", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["retrigger", "gate"], effectTypesDisplay: "Re, Ga", min: "0%", max: "100%", start_placeholder: "100%", end_placeholder: "50%" },
  { displayName: "update_trigger", parameterName: "update_trigger", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["retrigger", "echo"], effectTypesDisplay: "Re, Ec", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "mix", parameterName: "mix", support: "supported", unit: "%", valueType: "int", offValue: "0%", effectTypes: ["retrigger", "gate", "flanger", "pitch_shift", "bitcrusher", "phaser", "wobble", "tapestop", "echo", "peaking_filter", "high_pass_filter", "low_pass_filter"], effectTypesDisplay: "Almost every effects", min: "0%", max: "100%", start_placeholder: "0%", end_placeholder: "100%" },
  { displayName: "period", parameterName: "period", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["flanger", "phaser", "sidechain"], effectTypesDisplay: "Fl, Ph, SC", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "delay", parameterName: "delay", support: "supported", unit: "samples", valueType: "int", offValue: null, effectTypes: ["flanger"], effectTypesDisplay: "Fl", min: "0samples", max: "44100samples", start_placeholder: "0samples", end_placeholder: "30samples" },
  { displayName: "depth", parameterName: "depth", support: "supported", unit: "samples", valueType: "int", offValue: null, effectTypes: ["flanger"], effectTypesDisplay: "Fl", min: "0samples", max: "44100samples", start_placeholder: "0samples", end_placeholder: "45samples" },
  { displayName: "feedback", parameterName: "feedback", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["flanger", "phaser"], effectTypesDisplay: "Fl, Ph", min: "0%", max: "100%", start_placeholder: "35%", end_placeholder: "60%" },
  { displayName: "stereo_width", parameterName: "stereo_width", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["flanger", "phaser"], effectTypesDisplay: "Fl, Ph", min: "0%", max: "100%", start_placeholder: "0%", end_placeholder: "100%" },
  { displayName: "vol", parameterName: "vol", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["flanger"], effectTypesDisplay: "Fl", min: "0%", max: "100%", start_placeholder: "75%", end_placeholder: "75%" },
  { displayName: "pitch", parameterName: "pitch", support: "supported", unit: "key", valueType: "float", offValue: null, effectTypes: ["pitch_shift"], effectTypesDisplay: "PS", min: "-48", max: "48", start_placeholder: "0", end_placeholder: "12" },
  { displayName: "chunk_size", parameterName: "chunk_size", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["pitch_shift"], effectTypesDisplay: "PS", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "reduction", parameterName: "reduction", support: "supported", unit: "samples", valueType: "int", offValue: null, effectTypes: ["bitcrusher"], effectTypesDisplay: "BC", min: "0samples", max: "44100samples", start_placeholder: "0samples", end_placeholder: "30samples" },
  { displayName: "stage", parameterName: "stage", support: "unsupported", unit: "", valueType: "int", offValue: null, effectTypes: ["phaser"], effectTypesDisplay: "Ph", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "freq_1", parameterName: "freq_1", support: "supported", unit: "Hz", valueType: "int", offValue: null, effectTypes: ["phaser", "wobble"], effectTypesDisplay: "Ph, Wo", min: "10Hz", max: "20000Hz", start_placeholder: "1500Hz", end_placeholder: "2000Hz" },
  { displayName: "freq_2", parameterName: "freq_2", support: "supported", unit: "Hz", valueType: "int", offValue: null, effectTypes: ["phaser", "wobble"], effectTypesDisplay: "Ph, Wo", min: "10Hz", max: "20000Hz", start_placeholder: "20000Hz", end_placeholder: "15000Hz" },
  { displayName: "q", parameterName: "q", support: "supported", unit: "", valueType: "float", offValue: null, effectTypes: ["phaser", "wobble", "peaking_filter", "high_pass_filter", "low_pass_filter"], effectTypesDisplay: "Ph, Wo, PF, HPF, LPF", min: "0.1", max: "50", start_placeholder: "0.707", end_placeholder: "1.414" },
  { displayName: "hi_cut_gain", parameterName: "hi_cut_gain", support: "supported", unit: "dB", valueType: "float", offValue: null, effectTypes: ["phaser"], effectTypesDisplay: "Ph", min: "-60dB", max: "0dB", start_placeholder: "-8dB", end_placeholder: "0dB" },
  { displayName: "speed", parameterName: "speed", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["tapestop"], effectTypesDisplay: "TS", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "trigger", parameterName: "trigger", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["tapestop"], effectTypesDisplay: "TS", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "feedback_level", parameterName: "feedback_level", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["echo"], effectTypesDisplay: "Ec", min: "0%", max: "100%", start_placeholder: "35%", end_placeholder: "35%" },
  { displayName: "hold_time", parameterName: "hold_time", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["sidechain"], effectTypesDisplay: "SC", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "attack_time", parameterName: "attack_time", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["sidechain"], effectTypesDisplay: "SC", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "release_time", parameterName: "release_time", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["sidechain"], effectTypesDisplay: "SC", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "ratio", parameterName: "ratio", support: "supported", unit: "", valueType: "float", offValue: "1", effectTypes: ["sidechain"], effectTypesDisplay: "SC", min: "1", max: "100", start_placeholder: "1", end_placeholder: "5" },
  { displayName: "filename", parameterName: "filename", support: "unsupported", unit: "", valueType: null, offValue: null, effectTypes: ["switchaudio"], effectTypesDisplay: "SA", min: null, max: null, start_placeholder: null, end_placeholder: null },
  { displayName: "v", parameterName: "v", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["peaking_filter", "high_pass_filter", "low_pass_filter"], effectTypesDisplay: "PF, HPF, LPF", min: "0%", max: "100%", start_placeholder: "0%", end_placeholder: "100%" },
  { displayName: "gain", parameterName: "gain", support: "supported", unit: "%", valueType: "int", offValue: null, effectTypes: ["peaking_filter"], effectTypesDisplay: "PF", min: "0%", max: "100%", start_placeholder: "50%", end_placeholder: "50%" },
  { displayName: "freq", parameterName: "freq", support: "supported", unit: "Hz", valueType: "int", offValue: null, effectTypes: ["peaking_filter", "high_pass_filter", "low_pass_filter"], effectTypesDisplay: "PF, HPF, LPF", min: "10Hz", max: "20000Hz", start_placeholder: "100Hz", end_placeholder: "2000Hz" },
  { displayName: "freq_max", parameterName: "freq_max", support: "supported", unit: "Hz", valueType: "int", offValue: null, effectTypes: ["peaking_filter", "high_pass_filter", "low_pass_filter"], effectTypesDisplay: "PF, HPF, LPF", min: "10Hz", max: "20000Hz", start_placeholder: "100Hz", end_placeholder: "2000Hz" },
];

export const parameters = parameterDefinitions;
